controller_manager:
  ros__parameters:
    update_rate: 150  #Hz
    is_async: True

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    forward_current_controller:
      type: forward_command_controller/ForwardCommandController

    forward_effort_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    fts_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    uvms_controller:
      type: uvms_controller/UvmsController


# get vehicle base to manipulator base TF
# ros2 run tf2_ros tf2_echo base_link alpha_base_link 
    
uvms_controller:
  ros__parameters:
    dof:
      - floating_base
      - joint0
      - joint1
      - joint2
      - joint3 
      - endeffector

    floating_base:
      pose_topic_interface: ["position.x", "position.y", "position.z","position.qw","position.qx","position.qy","position.qz"]
      velocity_topic_interface: ["velocity.x","velocity.y","velocity.z","velocity.roll","velocity.pitch","velocity.yaw"]
      pose_command_interface: ["position.x", "position.y", "position.z","position.qw","position.qx","position.qy","position.qz"]
      velocity_command_interface: ["velocity.x","velocity.y","velocity.z","velocity.roll","velocity.pitch","velocity.yaw"]
      effort_command_interface: [effort.x, effort.y, effort.z, effort.roll, effort.pitch, effort.yaw]

    joint0:
      pose_topic_interface: ["filtered_position"]
      velocity_topic_interface: ["filtered_velocity"]
      pose_command_interface: ["position"]
      velocity_command_interface: ["velocity"]
      effort_command_interface: [effort]

    joint1:
      pose_topic_interface: ["filtered_position"]
      velocity_topic_interface: ["filtered_velocity"]
      pose_command_interface: ["position"]
      velocity_command_interface: ["velocity"]
      effort_command_interface: [effort]

    joint2:
      pose_topic_interface: ["filtered_position"]
      velocity_topic_interface: ["filtered_velocity"]
      pose_command_interface: ["position"]
      velocity_command_interface: ["velocity"]
      effort_command_interface: [effort]

    joint3:
      pose_topic_interface: ["filtered_position"]
      velocity_topic_interface: ["filtered_velocity"]
      pose_command_interface: ["position"]
      velocity_command_interface: ["velocity"]
      effort_command_interface: [effort]
      
    endeffector:
      pose_topic_interface: ["filtered_position"]
      velocity_topic_interface: ["filtered_velocity"]
      pose_command_interface: ["position"]
      velocity_command_interface: ["velocity"]
      effort_command_interface: [effort]

    agent:
      - alpha
      - beta

    # alpha:
    #   base_TF_translation: [0.140, 0.000, -0.120]
    #   base_TF_rotation: [3.142, 0.000, 0.000]
    #   joints:
    #     - alpha_IOs
    #     - alpha_axis_e
    #     - alpha_axis_d
    #     - alpha_axis_c
    #     - alpha_axis_b 
    #     - alpha_axis_a

    # beta:
    #   base_TF_translation: [0.140, 0.000, -0.120]
    #   base_TF_rotation: [3.142, 0.000, 0.000]
    #   joints:
    #     - beta_IOs
    #     - beta_axis_e
    #     - beta_axis_d
    #     - beta_axis_c
    #     - beta_axis_b 
    #     - beta_axis_a


joint_state_broadcaster:
  ros__parameters:
    map_interface_to_joint_state:
      effort: effort
      position: position
      velocity: velocity
      acceleration: acceleration
      current: current
      stateId: stateId

forward_position_controller:
  ros__parameters:
    joints:
      - alpha_axis_a
      - alpha_axis_b
      - alpha_axis_c
      - alpha_axis_d
      - alpha_axis_e
    interface_name: position

forward_velocity_controller:
  ros__parameters:
    joints:
      - alpha_axis_a
      - alpha_axis_b
      - alpha_axis_c
      - alpha_axis_d
      - alpha_axis_e
    interface_name: velocity

forward_current_controller:
  ros__parameters:
    joints:
      - alpha_axis_a
      - alpha_axis_b
      - alpha_axis_c
      - alpha_axis_d
      - alpha_axis_e
    interface_name: current

forward_effort_controller:
  ros__parameters:
    joints:
      - alpha_axis_a
      - alpha_axis_b
      - alpha_axis_c
      - alpha_axis_d
      - alpha_axis_e
    interface_name: effort