controller_manager:
  ros__parameters:
    update_rate: 150  #Hz
    is_async: True

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    forward_current_controller:
      type: forward_command_controller/ForwardCommandController

    forward_effort_controller:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    fts_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    uvms_controller:
      type: uvms_controller/UvmsController


# get vehicle base to manipulator base TF
# ros2 run tf2_ros tf2_echo base_link alpha_base_link 
    
uvms_controller:
  ros__parameters:
    base_TF_translation: [0.140, 0.000, -0.120]
    base_TF_rotation: [3.142, 0.000, 0.000]
    joints:
      - alpha_IOs
      - alpha_axis_e
      - alpha_axis_d
      - alpha_axis_c
      - alpha_axis_b 
      - alpha_axis_a

    thrusters:
      - alphathruster1_joint
      - alphathruster2_joint
      - alphathruster3_joint
      - alphathruster4_joint
      - alphathruster5_joint
      - alphathruster6_joint
      - alphathruster7_joint
      - alphathruster8_joint

    alpha_IOs:
      dynamics_identifier: "floating_base"
      pose_topic_interface: ["position.x", "position.y", "position.z","orientation.w","orientation.x","orientation.y","orientation.z"]
      velocity_topic_interface: ["velocity.u","velocity.v","velocity.w","velocity.p","velocity.q","velocity.r"]
      pose_command_interface: ["position.x", "position.y", "position.z","orientation.w","orientation.x","orientation.y","orientation.z"]
      velocity_command_interface: ["velocity.u","velocity.v","velocity.w","velocity.p","velocity.q","velocity.r"]
      effort_command_interface: [force.x, force.y, force.z, torque.x, torque.y, torque.z]

    alpha_axis_e:
      dynamics_identifier: "joint0"
      pose_topic_interface: ["filtered_position"]
      velocity_topic_interface: ["filtered_velocity"]
      pose_command_interface: ["position"]
      velocity_command_interface: ["velocity"]
      effort_command_interface: [effort]

    alpha_axis_d:
      dynamics_identifier: "joint1"
      pose_topic_interface: ["filtered_position"]
      velocity_topic_interface: ["filtered_velocity"]
      pose_command_interface: ["position"]
      velocity_command_interface: ["velocity"]
      effort_command_interface: [effort]

    alpha_axis_c:
      dynamics_identifier: "joint2"
      pose_topic_interface: ["filtered_position"]
      velocity_topic_interface: ["filtered_velocity"]
      pose_command_interface: ["position"]
      velocity_command_interface: ["velocity"]
      effort_command_interface: [effort]

    alpha_axis_b:
      dynamics_identifier: "joint3"
      pose_topic_interface: ["filtered_position"]
      velocity_topic_interface: ["filtered_velocity"]
      pose_command_interface: ["position"]
      velocity_command_interface: ["velocity"]
      effort_command_interface: [effort]
      
    alpha_axis_a:
      dynamics_identifier: "endeffector"
      pose_topic_interface: ["filtered_position"]
      velocity_topic_interface: ["filtered_velocity"]
      pose_command_interface: ["position"]
      velocity_command_interface: ["velocity"]
      effort_command_interface: [effort]



joint_state_broadcaster:
  ros__parameters:
    map_interface_to_joint_state:
      effort: effort
      position: position
      velocity: velocity
      acceleration: acceleration
      current: current
      stateId: stateId

forward_position_controller:
  ros__parameters:
    joints:
      - alpha_axis_a
      - alpha_axis_b
      - alpha_axis_c
      - alpha_axis_d
      - alpha_axis_e
      - alphathruster1_joint
      - alphathruster2_joint
      - alphathruster3_joint
      - alphathruster4_joint
      - alphathruster5_joint
      - alphathruster6_joint
      - alphathruster7_joint
      - alphathruster8_joint
    interface_name: position

forward_velocity_controller:
  ros__parameters:
    joints:
      - alpha_axis_a
      - alpha_axis_b
      - alpha_axis_c
      - alpha_axis_d
      - alpha_axis_e
      - alphathruster1_joint
      - alphathruster2_joint
      - alphathruster3_joint
      - alphathruster4_joint
      - alphathruster5_joint
      - alphathruster6_joint
      - alphathruster7_joint
      - alphathruster8_joint
    interface_name: velocity

forward_current_controller:
  ros__parameters:
    joints:
      - alpha_axis_a
      - alpha_axis_b
      - alpha_axis_c
      - alpha_axis_d
      - alpha_axis_e
      - alphathruster1_joint
      - alphathruster2_joint
      - alphathruster3_joint
      - alphathruster4_joint
      - alphathruster5_joint
      - alphathruster6_joint
      - alphathruster7_joint
      - alphathruster8_joint
    interface_name: current

forward_effort_controller:
  ros__parameters:
    joints:
      - alpha_axis_a
      - alpha_axis_b
      - alpha_axis_c
      - alpha_axis_d
      - alpha_axis_e
      - alphathruster1_joint
      - alphathruster2_joint
      - alphathruster3_joint
      - alphathruster4_joint
      - alphathruster5_joint
      - alphathruster6_joint
      - alphathruster7_joint
      - alphathruster8_joint
    interface_name: effort