/**:
  ros__parameters:
    fcu_url: "udp://:14770@192.168.2.1:14770"
    plugin_denylist:
      - ftp
      - px4flow
      - actuator_control
      - debug_value
      - global_position
      - distance_sensor
      - hil
      - extras
      - wheel_odometry
      - image_pub
      - vibration
      - gps*
      - setpoint*
      - gimbal_control
      - local_position
      - geofence
      - fake_gps
      - camera
      - mission
      - trajectory
      - wind_estimation

/**/imu:
  ros__parameters:
    frame_id: "robot_real_body_ned"
    # need find actual values
    # linear_acceleration_stdev: 0.0003
    # angular_velocity_stdev: 0.0003490659  # 0.02 degrees
    # orientation_stdev: 1.0
    # magnetic_stdev: 0.0
    # plugin_allowlist:
    #   - sys_status

